# Generated by Django 5.1.6 on 2025-10-10 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente_no_registrado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialPacNoRegistradoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_historial', models.DateField()),
                ('sintoma', models.CharField(max_length=250, null=True)),
                ('diagnostico', models.TextField(null=True)),
                ('observacion', models.TextField(null=True)),
                ('reserva_uuid', models.CharField(max_length=250, null=True)),
                ('fk_pac_no_registrado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paciente_no_registrado', to='paciente_no_registrado.pacientenoregistermodel')),
            ],
        ),
    ]
