# Generated by Django 5.1.6 on 2025-10-10 16:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente_no_registrado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion_reserva', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario_creacion_reserva', models.CharField(max_length=250, null=True)),
                ('fecha_reserva', models.DateField()),
                ('hora_inicio', models.TimeField(default='00:00:00')),
                ('hora_termino', models.TimeField(default='00:00:00')),
                ('especialidad', models.CharField(max_length=200, null=True)),
                ('nombre_doctor', models.CharField(max_length=250, null=True)),
                ('tipo_pago', models.CharField(max_length=250, null=True)),
                ('reserva_uuid', models.CharField(max_length=250, null=True)),
                ('nombre_clinica', models.CharField(max_length=250, null=True)),
                ('comuna_clinica', models.CharField(max_length=250, null=True)),
                ('direccion_clinica', models.CharField(max_length=250, null=True)),
                ('reserva_cerrada', models.IntegerField(blank=True, default=0, null=True)),
                ('pago_realizado', models.IntegerField(blank=True, default=0, null=True)),
                ('fk_pac_no_register', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='paciente_no_registrado.pacientenoregistermodel')),
            ],
        ),
    ]
