# Generated by Django 5.1.6 on 2025-10-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consulta',
            old_name='nombre',
            new_name='primer_nombre',
        ),
        migrations.AddField(
            model_name='consulta',
            name='segundo_nombre',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
