# Generated by Django 5.1.6 on 2025-10-14 20:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0002_rename_nombre_consulta_primer_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='consulta_cerrada',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='consulta',
            name='fecha_creacion_reserva',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='consulta',
            name='nombre_usuario',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
