# Generated by Django 5.1.6 on 2025-10-14 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0003_consulta_consulta_cerrada_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Consulta',
            new_name='ConsultaModel',
        ),
    ]
