# Generated by Django 5.1.6 on 2025-10-15 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0004_rename_consulta_consultamodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultamodel',
            old_name='fecha_creacion_reserva',
            new_name='fecha_creacion_consulta',
        ),
    ]
