# Generated by Django 5.1.6 on 2025-10-15 17:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0005_rename_fecha_creacion_reserva_consultamodel_fecha_creacion_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultamodel',
            name='fecha_respuesta',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
