# Generated by Django 5.1.6 on 2025-10-15 17:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0006_consultamodel_fecha_respuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultamodel',
            name='fecha_respuesta',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
