# Generated by Django 5.1.6 on 2025-10-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0007_alter_consultamodel_fecha_respuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultamodel',
            name='respuesta',
            field=models.TextField(null=True),
        ),
    ]
