# Generated by Django 5.1.6 on 2025-10-10 16:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DescuentoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('nombre_descuento', models.TextField(max_length=250, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cod_descuento', models.TextField(blank=True, null=True)),
                ('descuento', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_termino', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DescuentoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pagar', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_pagar_descuento', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_utilizacion', models.DateField(default=django.utils.timezone.now)),
                ('fk_descuento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='descuento.descuentomodel')),
            ],
        ),
    ]
