# Generated by Django 5.1.6 on 2025-10-10 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('descuento', '0001_initial'),
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='descuentopaciente',
            name='fk_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.pacientemodel'),
        ),
        migrations.AddField(
            model_name='descuentomodel',
            name='descuento_paciente',
            field=models.ManyToManyField(related_name='descuentos_asignados', through='descuento.DescuentoPaciente', to='paciente.pacientemodel'),
        ),
    ]
