# Generated by Django 5.1.6 on 2025-10-10 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comuna_clinica', '0001_initial'),
        ('secretaria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='secretariamodel',
            name='fk_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='secretariamodel',
            name='secretaria_clinica',
            field=models.ManyToManyField(to='comuna_clinica.comunaclinicamodel'),
        ),
    ]
